"""drop employee.user_id

Revision ID: 8e4dea904b59
Revises: c0e5dbbbcfd6
Create Date: 2025-09-10 11:24:37.357376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4dea904b59'
down_revision: Union[str, Sequence[str], None] = 'c0e5dbbbcfd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_user_id_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employees_user_id_fkey'), 'employees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
